#!/usr/bin/env bash
#  a Bash script that configures a new Ubuntu machine
#  by installing a web server Nginx

apt-get update -y
apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo ufw allow 'Nginx HTTP'
service nginx restart
