#!/usr/bin/env bash
# A script that configure HAproxy on my lb server.

# install haproxy
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install -y haproxy=2.8.\*

# enable haproxy
sudo echo "ENABLED=1" >> /etc/default/haproxy

# duplicate config file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bk

# server configuration
printf %s "
listen 331620-lb-01
	bind 0.0.0.0:80
	mode http
	stats enable
	stats uri /haproxy?stats
	stats realm Strictly\ Private
	balance roundrobin
	option httpclose
	option forwardfor
	server 331620-web-01 54.87.251.103:80 check
	server 331620-web-02 54.236.52.59:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
