#!/usr/bin/env bash
# a script that backs up a mysql database.

if [ "$#" -ne 1 ]
then
    exit 1
fi

current_date=$(date +"%d-%m-%Y")

# generate backup
mysqldump -u root --password="$1" -A > backup.sql 2>/dev/null

# compress backup
tar -czvf "$current_date".tar.gz backup.sql

exit 0
