#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=: read -r username pwd uid gid uidinfo home shell; do
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pwd, more info about the user here: $uidinfo"
done < /etc/passwd
