#!/usr/bin/env bash
# printing "Best School" 10 times
# but for the 4th and 8th iter displays something else

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo 'bad luck'
	elif [ $i -eq 7 ]
	then
		echo 'good luck'
	else
		echo 'Best School'
	fi
	((i++))
done
