#!/usr/bin/env bash
# a Bash script that gives you information about the school file.

filepath="school"

if [ -e "$filepath" ]; then
	echo "school file exists"

	if [ -s "$filepath" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "$filepath" ]; then
		echo "school file is a regular file"
	fi
else
	echo "school file does not exist"
fi
