#!/usr/bin/env bash
# A script that installs ufw and sets it up.

sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable
sudo systemctl restart nginx
